name: Render pbrt-v4.pdf
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  render-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: typst-community/setup-typst@v3
      - run: typst --version
      - run: typst fonts --font-path ./fonts
      - run: mkdir output
      # Now Typst is installed and packages will be cached!
      - run: typst c main.typ ./output/pbrt-v4-zh-en-$(git describe --tags --abbrev=0).pdf --font-path ./fonts
      - run: typst c main.typ ./output/pbrt-v4-zh-$(git describe --tags --abbrev=0).pdf --font-path ./fonts  --input LANG_OUT=zh
      - run: typst c main.typ ./output/pbrt-v4-en-$(git describe --tags --abbrev=0).pdf --font-path ./fonts  --input LANG_OUT=en
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.txt
          draft: true
          files: |
            ./output/*.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pdfs
          path: output/*.pdf
